### ISSUE TITLE
Include timings at the end of each bar.

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#31]
https://github.com/h2oai/db-benchmark/issues/27#issuecomment-420368311
> It would be nice to place the timing in seconds at the end of each bar, too. Say "7.3s; 7.1s" in small text at the end of each bar for the 1st and 2nd timing. Just to read off the timings extremely easily and conveniently.

**Comment by jangorecki** [comment]
@mattdowle adding 1st run timing together with 2nd run timing might not be as much read-able. Will add timing of first run for now.

**Comment by jangorecki** [comment]
it might be a little bit misleading, when second run is slower than first run, then value of 1st run is printed next to 2nd run bar. To prevent overlapping of text and 2nd run bar. Maybe we can use `max(1run, 2run)` for as text then?

**Comment by mattdowle** [comment]
Agreed. `max(1run, 2run)` looks good to me.

**Comment by jangorecki** [comment]
there is suggestion to include both timings as values, they can be aligned on the `max` of two, so none would be overlapping on bars

**Comment by mattdowle** [comment]
+1 to showing both timings.   But just as important (more so) is printing those figures in the whitespace after the end of the chopped-off bars.  Since both 1st and 2nd run bars are chopped-off,  it will be really nice to see the figures printed.   Currently the text is hard to read with it being on top of the bar and it's not immediately obvious that the bar is chopped.   If the text could start with "..." for those,  it would be clearer;  e.g.  " ...  4.17; 3.93".       But for this the page/image width limitation needs to be solved.

**Comment by jangorecki** [comment]
we now have both values.
having them outside the plot region will need to wait as we currently does not have margin there,

**Comment by mattdowle** [comment]
Looks great.  Thanks!
