### ISSUE TITLE
Add data ingest timings

### ISSUE THREAD

**Issue by mattdowle** [h2oai/db-benchmark#37]
Need to clear OS cache before each 1st run; e.g. using `sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'`. I'd say that the 2nd run should be allowed to benefit from the OS cache and we'd expect the 2nd run to be faster.   One option is that variance can be obtained using a time series of daily observations of 1st and 2nd runs.  Another option is to repeat the drop cache and do the 1st and 2nd run a second time (4 timings total).  In this case of data ingest, a 3rd run may be benefit (6 timings total), since OS cache affects the 1st run.  Although, 6 runs may push the limits of what can be achieved within a single 24hr period since db-bench total time is at 5hrs currently before the addition of dask.

Aside: since db-bench reruns on the same machine each day,  there's a chance that yesterday's run affects today's run in various ways.  So perhaps a daily machine reboot should be considered to remove any possibility of that. In other words: even if it's proved that a machine reboot doesn't make a jot of difference, still do it anyway, for the avoidance of doubt.

**Comment by jangorecki** [comment]
@mattdowle is it fine to drop caches only before first run of a first question? then that could be incorporated into script which orchestrates running benchmark. If we want to drop caches before first run of each single question, then all the scripts have to be changed to run those drop caches, using sudo, and that makes it more tricky.

**Comment by jangorecki** [comment]
I agree that would be very useful, but I don't really see that to be reliably implemented here.
Clearing caches between each query will require system calls to sudo command between each query. And at least from R, such system calls are likely to fail (with warning, not stop) on 1e9 data size (k=10 and k=2 most often), due to the problem described in [.Internal(quit(...)): system call failed: Cannot allocate memory](https://stat.ethz.ch/pipermail/r-devel/2020-November/080135.html). In short, when R runs close to memory limits, it fails to execute system calls with "cannot allocate memory" warning. Clearing caches between run of each script is more easily doable, but I don't it really address the problem. I would close this issue.
