### ISSUE TITLE
Report the history of benchmark timings

### ISSUE THREAD

**Issue by st-pasha** [h2oai/db-benchmark#46]
It would be great to automatically produce a chart where X axis is the date, Y axis the benchmarking timing, and the values plotted are limited to a particular package + question. Multiple lines may be present to show single package/several questions; or multiple packages/single question.

This chart would allow us to view how the timings changed over time, and in particular, identify any possible performance regressions. 

We could use a JS library like [Flot](http://www.flotcharts.org/flot/examples/) to make the chart directly in the browser.

**Comment by jangorecki** [comment]
Good idea. One of the goals of that project at current stage is to keep the report simple. That basically means limiting the amount of information we present to user. Ideally would be to have simple summary, and a "browser" for arbitrary queries of timings data, so these kind of questions could be answered too. And because now we generate static html from Rmarkdown there is not that much flexibility in providing interactive interface for that.
As side note I will that such feature will require new field which will uniquely identify machine that run benchmark. We will migrate soon production to different machine having GPUs. CPU will increase from 32 to 40, memory will stay the same. So the timing will be slightly different since that.

**Comment by jangorecki** [comment]
for now we can spot regression for all solutions for 1e9 with this
```r
DT = data.table::fread("time.csv")
dt = DT[solution%in%c("data.table","dplyr","pandas","pydatatable","spark","dask","juliadf")]
lattice::xyplot(time_sec ~ batch | solution+data, dt[task=="groupby"&in_rows==1e9&run==1L&!is.na(batch)&!is.na(time_sec)][order(batch)], type="l", groups=question, auto.key=list(points=FALSE, columns=2, lines=TRUE), scales=list(relation="free"))
```
