### ISSUE TITLE
Julia queries should not include compilation time

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#69]
As a follow up from comments #12 putting that into own issue. @nalimilan 

> > Cheating would be looking at the data. We can use dummy 0 rows dataframe of exact structure, which is a metadata, not data itself. Run query on that to compile commands. Will that work? IMO this will not be cheating because we know upfront what questions we want to ask against data. Assuming the task does not meant to reflect interactive data queries scenario but more a predefined processing workflow scenario @mattdowle.
> 
> Yes, that would work. Anyway the data shouldn't make any difference for Julia, only the column types. So you could do `dummydf = df[1:1, :]` and run queries on that first. But even running an arbitrary query would already eliminate a large part of the overhead, which is shared across operations.

**Comment by jangorecki** [comment]
@nalimilan assuming we don't want to touch data - so instead of `df[1:1, :]` which already filters data - we have to create 0-1 rows dataframe "by hand". Which is fine, unless some column might have different type depending on `categoricals=0.05` in CSV reader. What is proper way to construct such dummy dataframe just by obtaining column types from `df`?

**Comment by nalimilan** [comment]
You can do `df2 = similar(df, 0)` to get an empty data frame with the same column types as `df` but zero lines. Then you can add rows with arbitrary data with e.g. `push!(df2, (1, "a"))`. You can also do `similar(df, 1)` to get an uninitialized row, that you can then fill using the normal indexing syntax (numeric values will be filled with uninitialized values, but others are undefined and need to be set manually).

Overall, taking the first row is simpler. Of course it uses real data, but it cannot possibly help an implementation to be faster on the next run.

**Comment by st-pasha** [comment]
I'm not sure I understand the "fairness" logic here. I feel it would be useful to be very specific and very explicit in this regard.

As for precompiling, aren't all packages doing it internally anyways? The `data.table` has 1500+ lines of code converting R i-j-by expressions into the representation suitable for calling the internal C code. SQL engines have sophisticated query analyzers/optimizers. This is all compiling. Different solutions use different strategies for this. Some can compiler once and then reuse the results in subsequent queries, others cannot. Some use high-level languages during compilation, others more optimized low-level languages. Some use internal data stats to decide how to run the query optimally. Others use the types of data that participate in the query. There are solutions that can adjust and switch strategies on the fly. Obviously, the solutions also differ in how exactly they perform compilation. A Java-based library may create new classes on the fly or just rely on JIT compiling; a C/C++ solution may compile into internal structure describing what needs to be done; an LLVM-based solution can compile machine-level code, though it usually takes much longer; python can compile python code into internal byte-code; etc, etc. 

So, what exactly are the guidelines to ensure that all solutions are tested on equal grounds?

**Comment by mattdowle** [comment]
I added some thoughts here:  https://github.com/h2oai/db-benchmark/issues/60#issuecomment-456198103.

**Comment by jangorecki** [comment]
Great to see so much feedback here.

@nalimilan any idea how spark is handling that problem? we might have to add grouping on dummy/empty dataset for all solutions to be fair.

> So, what exactly are the guidelines to ensure that all solutions are tested on equal grounds?

That is obviously not easy to define. I would say that using the API of language and a solution while not looking at data, but knowing the schema and question that are going to be asked. As mentioned below to simulate "data processing workflow". Using the API is a tricky thing because for example in R you can write C function from R and use in same session. I would say that code has to written in the most-common way for a solution to achieve the results.

Quoting @mattdowle from issue linked above

> What we're trying to mimic and represent fairly is the user experience. In my own experience I rarely needed to compute the same answer many times

This is fundamental question. Do we want to cover an user's interactive data queries or a data processing workflow. In the first case questions that we might want to ask on that data are unknown, in the latter only the data are unknown.
I argue to focus on the latter case. I believe that total timing of "data processing workflows" around the world is overwhelmingly larger than total timing of "user's interactive data queries". Just because workflows runs regularly. Aside from that "user's behavior" cannot be precisely defined.

> Especially in production there was a task that ran once...

This fits more into "a data processing workflow".

> Just to say as well that we do want to do end-to-end benchmarks too

That seems to be better place to include the cost of compilation then.

**Comment by mattdowle** [comment]
To follow up on things I've been quoted on to clarify ...

There is a wide range of use-cases.
There is a wide range of users.
Many users have a wide range of use-cases simultaneously.

On db-bench we're not trying to pick. We shouldn't try and focus. The overriding goal is to be transparent and be helpful to all the users with all the use-cases so they can decide for themselves. That's why we include the 1st and the 2nd run and present both.  I've said that it was the 1st run that was most important to me most often in the past because I was justifying why the 1st run is included and reported. I was not saying that because that's what I think we should focus on, although I see how that may have been how it came across. Other users will look at the 2nd run time and know that's more applicable to their use-case. [Aside: it's kind of assumed that runs 3-100 are very close to run 2; that run 1 is the outlier. We want to build a check on that in, say by performing run 3 and maybe 4 too. But total runtime is already 37 hours so that's going to be interesting from the resource point of view. ]
 
There were situations where I did a `setkey()` first (an up-front cost) to get a speed benefit later if I was using the same key many times in different queries later.  In my view the goal of db-bench is to benchmark those trade-offs transparently so users can decide for themselves for their use-case. The user needs to know how long does a `setkey()` take (and the equivalent for each of the products) and is it worth it.  This issue about Julia compilation seems similar to that.

If the advice to Julia users is to run `dummydf=df[1:1, :]` and run queries on that first as a way to trigger one-time compilation, then whatever those queries are could be placed in a function `JuliaDF.compile()` and chalked up to Julia startup time. Users could just put that in their startup profile script. We don't currently display how long Python or R takes to start, but if we do (and it is important in some use-cases where many processes are started) then the time for `JuliaDF.compile()` could be included there.

But note that the culprit being Julia compilation time was only a quick theory (by the julia team) and it's likely not to do with compilation time after all.  These are exactly the sort of inferences that db-bench is there to eek out transparently and why it's so important that it reruns regularly using latest dev versions.

**Comment by mattdowle** [comment]
> with the same schema as the actual one
I hadn't grasped that part before. Then it's something the user experiences and needs to know about and run, so shouldn't be excluded from db-bench.  There could maybe be an extra manual warm up task 0 reported separately but only Julia would need that.

**Comment by nalimilan** [comment]
OK, let me discuss this with others. We could certainly provide a function or script which would trigger compilation of functions for all common types. It would take a relatively long time if done thoroughly, so I wouldn't want to run it by default, but reporting the time it takes separately would definitely make sense.

**Comment by jangorecki** [comment]
cuDF and ClickHouse has been recently added benchmark. They suffer more badly than juliadf in terms of the issue discussed here.
IMO we should not skip compilation time, but still allow Julia/others to optimise that internally. So basically what Matt suggested
> If there's a way to compile all types up front in each session, before knowing anything about the data, then I'd say it's totally fair

Closing this issue for now, as there is nothing we can do about that here.
If such feature will be added to Julia DF please let us know, or fill PR directly to activate it.
