### ISSUE TITLE
add dtplyr that means data.table with dplyr syntax.

### ISSUE THREAD

**Issue by mrchypark** [h2oai/db-benchmark#76]
How about dtplyr?

dtplyr package provide function that can use dplyr syntax with data.table class.

https://github.com/hadley/dtplyr

**Comment by jangorecki** [comment]
Thanks for filling this suggestion. The only problem now about dtplyr is that it is not actively maintained. There are few commits in February but not really what is required there. As of now it make sense to run it once to see how it performs but not much make sense to have that in benchmark scheduler.

**Comment by mrchypark** [comment]
Make sense. Thank you for consider this option.

**Comment by jangorecki** [comment]
best will be to get back to this when dtplyr will be maintained again

**Comment by jangorecki** [comment]
dtplyr is now actively maintained
Although I don't think so we should be adding it to benchmark. We could assume it will be similarly fast as data.table. We don't want to benchmark translation layer (which dtplyr is) but task algorithm implementations. Otherwise it would also make sense to add sparklyr, spark from scala, etc.
